services:
  db:
    image: postgres:16
    container_name: pg-restaurant
    restart: unless-stopped
    environment:
      POSTGRES_DB: restaurant_review_db
      POSTGRES_USER: rest_user
      POSTGRES_PASSWORD: rest_pass123!
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rest_user -d restaurant_review_db"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata: